import {
  PREP_AUTOMATION_TABS,
  PROJECT_SETUP_TABS,
  SCORECARD_TABS,
  SHEET_IDS,
  displayScheduleStatus,
  normalizeScheduleStatus,
} from './operations-contract';

const PROJECT_SETUP_SHEET_ID = SHEET_IDS.projectSetup;
const PREP_AUTOMATION_SHEET_ID = SHEET_IDS.projectPrepAutomation;
const LEVEL10_SHEET_ID = SHEET_IDS.level10;
const SCORECARD_SHEET_ID = SHEET_IDS.scorecardHub;

type CsvRow = string[];

export interface ProjectPrepSource {
  key: string;
  label: string;
  spreadsheetId: string;
  tab: string;
  owner: 'source_of_truth' | 'supporting' | 'legacy_or_audit';
  use: string;
  url: string;
}

export interface ProjectPrepResource {
  key: string;
  label: string;
  required: boolean;
  primary: string;
  accountStatus: string;
  pendingApp: string;
  alternates: string[];
  searchCity: string;
  status: 'READY' | 'CHECK' | 'NO ACCOUNT' | 'NOT REQUIRED' | 'MISSING';
  riskLevel: 'ready' | 'watch' | 'blocked' | 'neutral';
  nextAction: string;
  riskNote: string;
  source: string;
}

export interface ProjectPrepBlocker {
  jobNumber: string;
  label: string;
  severity: 'blocked' | 'watch';
  reason: string;
  nextAction: string;
  source: string;
}

export interface ProjectPrepJob {
  jobId: string;
  jobNumber: string;
  jobName: string;
  wipStatus: string;
  address: string;
  city: string;
  state: string;
  generalContractor: string;
  pointOfContact: string;
  planDate: string;
  latitude: number | null;
  longitude: number | null;
  asphaltSource: string;
  quarrySource: string;
  estimatedTons: number;
  estimatedLoads: string;
  needs: Record<string, boolean>;
  schedule: {
    scheduledStart: string;
    scheduledFinish: string;
    crew: string;
    mobilizeReady: string;
    weatherRisk: string;
    notes: string;
  };
  scope: {
    workOrderLink: string;
    jobFolderLink: string;
    asphalt: string;
    milling: string;
    base: string;
    demo: string;
    drainage: string;
    fieldEvents: string;
    source: string;
  };
  links: {
    level10: string;
    projectSetup: string;
    prepAutomation: string;
    scorecard: string;
    jobFolder: string;
    workOrder: string;
    costSheet: string;
    plans: string;
    contract: string;
  };
  resources: ProjectPrepResource[];
  blockers: ProjectPrepBlocker[];
  weather: {
    forecastDate: string;
    rainPercent: number | null;
    conditions: string;
    risk: string;
    source: string;
  };
  nearbyJobs: Array<{
    jobNumber: string;
    jobName: string;
    city: string;
    state: string;
    miles: number;
  }>;
  equipment: {
    rentals: Array<{
      vendor: string;
      contractNumber: string;
      equipmentType: string;
      daysOnRent: number;
      pickupDate: string;
    }>;
    assets: Array<{
      assetId: string;
      make: string;
      model: string;
      status: string;
      lastReported: string;
      distanceMiles: number | null;
    }>;
  };
  actions: Array<{
    label: string;
    href: string;
    source: string;
  }>;
  readiness: {
    readyCount: number;
    requiredCount: number;
    watchCount: number;
    blockerCount: number;
    readyPercent: number;
    status: 'READY' | 'REVIEW' | 'BLOCKED';
    funnel: Array<{
      label: string;
      complete: boolean;
      detail: string;
    }>;
  };
}

export interface ProjectPrepPayload {
  generatedAt: string;
  sources: ProjectPrepSource[];
  sourceOfTruth: Array<{
    dataType: string;
    source: string;
    reason: string;
  }>;
  issues: string[];
  summary: {
    activeJobs: number;
    readyJobs: number;
    reviewJobs: number;
    blockedJobs: number;
    openBlockers: number;
  };
  jobs: ProjectPrepJob[];
}

const SOURCES: ProjectPrepSource[] = [
  source('project_setup_active_jobs', 'Active job identity and coordinates', PROJECT_SETUP_SHEET_ID, PROJECT_SETUP_TABS.activeJobs, 'source_of_truth', 'Canonical active prep job list, location, need flags, source vendors.'),
  source('project_setup_prep_board', 'Readiness board', PROJECT_SETUP_SHEET_ID, PROJECT_SETUP_TABS.jobPrepBoard, 'source_of_truth', 'Canonical resource readiness, account status, alternates, blockers, next actions.'),
  source('scorecard_ms_project_schedule', 'Schedule timeline', SCORECARD_SHEET_ID, SCORECARD_TABS.msProjectScheduleLive, 'source_of_truth', 'Live Microsoft Project schedule import normalized for prep readiness.'),
  source('project_setup_vendor_resources', 'Vendor and resource masters', PROJECT_SETUP_SHEET_ID, 'Asphalt_Plants / Quarries_Rock / Concrete / Haulers / Dump_Sites / Misc_Supplies / Equipment_Vendors / Credit_Accounts', 'source_of_truth', 'Vendor setup and account context.'),
  source('project_setup_job_docs', 'Job document links', PROJECT_SETUP_SHEET_ID, PROJECT_SETUP_TABS.jobDocs, 'source_of_truth', 'Cost sheet, work order, plan, and contract links generated by Apps Script.'),
  source('prep_automation_parsed_jobs', 'Work-order scope extraction', PREP_AUTOMATION_SHEET_ID, PREP_AUTOMATION_TABS.parsedJobs, 'supporting', 'Parsed scope, original work order link, job folder link, extracted material sources.'),
  source('prep_automation_audit', 'Legacy automation audit', PREP_AUTOMATION_SHEET_ID, `${PREP_AUTOMATION_TABS.jobSetup} / ${PREP_AUTOMATION_TABS.taskBoard}`, 'legacy_or_audit', 'Older generated setup requirements and task-board rows. Read-only audit source.'),
  source('level10_schedule', 'Level 10 schedule support', LEVEL10_SHEET_ID, 'SCHEDULE_DATA / JOB_MAP', 'supporting', 'Crew schedule context and nearby/related job support when prep schedule is blank.'),
  source('scorecard_ops', 'Operations scorecard support', SCORECARD_SHEET_ID, `${SCORECARD_TABS.masterJobs} / ${SCORECARD_TABS.weatherWatch} / ${SCORECARD_TABS.visionLinkEquipment} / ${SCORECARD_TABS.onRent}`, 'supporting', 'Operational, weather, rental, and equipment context.'),
];

const SOURCE_OF_TRUTH = [
  {
    dataType: 'Active job list, job identity, state, city, coordinates, need flags',
    source: `Sunbelt Project Setup -> ${PROJECT_SETUP_TABS.activeJobs}`,
    reason: 'This sheet has the current 10 prep jobs and the same job set rendered by the live Project Prep page.',
  },
  {
    dataType: 'Readiness status, vendor/account blockers, alternates, next actions',
    source: `Sunbelt Project Setup -> ${PROJECT_SETUP_TABS.jobPrepBoard}`,
    reason: 'This is the operational readiness board with one row per job/resource segment.',
  },
  {
    dataType: 'Schedule, mobilization readiness, schedule weather review',
    source: `Sunbelt Sports Scorecard -> ${SCORECARD_TABS.msProjectScheduleLive}`,
    reason: 'The Project Setup workbook does not currently contain a Schedule tab; the live Microsoft Project import is the schedule contract used by the dashboard.',
  },
  {
    dataType: 'Scope, work-order extraction, folder/work-order links',
    source: `Project Prep Automation Center -> ${PREP_AUTOMATION_TABS.parsedJobs}`,
    reason: 'This is the only inspected source with parsed scope fields and original work-order links.',
  },
  {
    dataType: 'Vendor/resource master data',
    source: 'Sunbelt Project Setup -> resource tabs and Credit_Accounts',
    reason: 'These tabs share one normalized vendor/account schema and feed the prep board alternates.',
  },
  {
    dataType: 'Equipment rentals and basic equipment visibility',
    source: `Sunbelt Project Setup rentals when present, plus Sunbelt Sports Scorecard -> ${SCORECARD_TABS.onRent} / ${SCORECARD_TABS.visionLinkEquipment}`,
    reason: 'The Project Setup workbook does not currently contain live rental or VisionLink tabs; scorecard tabs are the inspected live operational fallback.',
  },
  {
    dataType: 'Company-wide scorecard and operations context',
    source: 'Sunbelt Sports Scorecard',
    reason: 'Supporting only. Its Project Prep and Weather tabs are currently header-only for this workflow.',
  },
];

const RESOURCE_ORDER = [
  'Asphalt Plant',
  'Rock / Quarry',
  'Concrete / Field Events',
  'Haulers / Trucks',
  'Dump Site / Debris',
  'Equipment On Rent',
  'Misc Supplies',
];

export async function fetchProjectPrepCenter(): Promise<ProjectPrepPayload> {
  const [
    activeRows,
    prepRows,
    scheduleRows,
    weatherRows,
    docsRows,
    parsedRows,
    rentalsRows,
    equipmentRows,
  ] = await Promise.all([
    fetchSheetRows(PROJECT_SETUP_SHEET_ID, PROJECT_SETUP_TABS.activeJobs),
    fetchSheetRows(PROJECT_SETUP_SHEET_ID, PROJECT_SETUP_TABS.jobPrepBoard),
    fetchNormalizedPrepScheduleRows(),
    fetchNormalizedPrepWeatherRows(),
    fetchSheetRows(PROJECT_SETUP_SHEET_ID, PROJECT_SETUP_TABS.jobDocs),
    fetchSheetRows(PREP_AUTOMATION_SHEET_ID, PREP_AUTOMATION_TABS.parsedJobs),
    fetchProjectPrepRentalRows(),
    fetchSheetRows(SCORECARD_SHEET_ID, SCORECARD_TABS.visionLinkEquipment),
  ]);

  const active = tableFromRows(activeRows, ['Job Number', 'Job Name']);
  const prep = tableFromRows(prepRows, ['Prep_ID', 'Job Number', 'Prep Item']);
  const schedule = tableFromRows(scheduleRows, ['Job Number', 'Job Name', 'Mobilize Ready?']);
  const weather = tableFromRows(weatherRows, ['Job Number', 'Job Name', 'Risk']);
  const docs = tableFromRows(docsRows, ['Job Number', 'Job Name']);
  const parsed = tableFromRows(parsedRows, ['Job Number', 'Job Name', 'Work Order Link']);
  const rentals = tableFromRows(rentalsRows, ['Vendor', 'Contract_Number']);
  const equipment = tableFromRows(equipmentRows, ['AssetID', 'Make']);

  const issues = detectContractIssues(activeRows, active.header, prep.rows, schedule.rows);
  const prepByJob = groupBy(prep.rows, row => cell(row, ['Job Number'], 1));
  const scheduleByJob = indexBy(schedule.rows, row => cell(row, ['Job Number', 'Clean_Job_Num'], 0));
  const weatherByJob = indexBy(weather.rows, row => cell(row, ['Job Number'], 0));
  const docsByJob = indexBy(docs.rows, row => cell(row, ['Job Number'], 0));
  const parsedByJob = indexBy(parsed.rows, row => cell(row, ['Job Number'], 0));
  const allJobsBase = active.rows
    .map(row => buildJobBase(row))
    .filter(job => /^\d{2}-\d{3}$/.test(job.jobNumber));

  const liveWeather = await fetchLiveWeather(allJobsBase);

  const jobs = allJobsBase.map(base => {
    const prepItems = prepByJob[base.jobNumber] || [];
    const scheduleRow = scheduleByJob[base.jobNumber];
    const weatherRow = weatherByJob[base.jobNumber];
    const docsRow = docsByJob[base.jobNumber];
    const parsedRow = parsedByJob[base.jobNumber];
    const resources = buildResources(base, prepItems);
    const blockers = buildBlockers(base.jobNumber, resources);
    const readiness = buildReadiness(base, parsedRow, scheduleRow, resources, blockers);
    const links = buildLinks(base, parsedRow, docsRow);
    const jobWeather = buildWeather(base, weatherRow, liveWeather[base.jobNumber]);
    const nearbyJobs = buildNearbyJobs(base, allJobsBase);
    const jobEquipment = buildEquipment(base, rentals.rows, equipment.rows);
    const actions = buildActions(base, blockers, links);

    return {
      ...base,
      schedule: {
        scheduledStart: cell(scheduleRow, ['Scheduled Start'], 4),
        scheduledFinish: cell(scheduleRow, ['Scheduled Finish'], 5),
        crew: cell(scheduleRow, ['Crew'], 6),
        mobilizeReady: cell(scheduleRow, ['Mobilize Ready?'], 7),
        weatherRisk: cell(scheduleRow, ['Weather Risk'], 8),
        notes: cell(scheduleRow, ['Notes'], 9),
      },
      scope: {
        workOrderLink: cell(parsedRow, ['Work Order Link'], 2),
        jobFolderLink: cell(parsedRow, ['Job Folder Link'], 3),
        asphalt: cell(parsedRow, ['Asphalt Scope'], 11),
        milling: cell(parsedRow, ['Milling Scope'], 12),
        base: cell(parsedRow, ['Base/GAB Scope'], 13),
        demo: cell(parsedRow, ['Demo Scope'], 14),
        drainage: cell(parsedRow, ['Drainage Scope'], 15),
      fieldEvents: cell(parsedRow, ['Field Events Scope'], 16),
        source: parsedRow ? `Project Prep Automation Center -> ${PREP_AUTOMATION_TABS.parsedJobs}` : `Missing ${PREP_AUTOMATION_TABS.parsedJobs} match`,
      },
      links,
      resources,
      blockers,
      weather: jobWeather,
      nearbyJobs,
      equipment: jobEquipment,
      actions,
      readiness,
    };
  });

  const readyJobs = jobs.filter(job => job.readiness.status === 'READY').length;
  const blockedJobs = jobs.filter(job => job.readiness.status === 'BLOCKED').length;
  const reviewJobs = jobs.length - readyJobs - blockedJobs;
  const openBlockers = jobs.reduce((sum, job) => sum + job.blockers.length, 0);

  return {
    generatedAt: new Date().toISOString(),
    sources: SOURCES,
    sourceOfTruth: SOURCE_OF_TRUTH,
    issues,
    summary: {
      activeJobs: jobs.length,
      readyJobs,
      reviewJobs,
      blockedJobs,
      openBlockers,
    },
    jobs,
  };
}

function source(
  key: string,
  label: string,
  spreadsheetId: string,
  tab: string,
  owner: ProjectPrepSource['owner'],
  use: string,
): ProjectPrepSource {
  return {
    key,
    label,
    spreadsheetId,
    tab,
    owner,
    use,
    url: `https://docs.google.com/spreadsheets/d/${spreadsheetId}/edit`,
  };
}

async function fetchSheetRows(sheetId: string, tabName: string): Promise<CsvRow[]> {
  const url = `https://docs.google.com/spreadsheets/d/${sheetId}/gviz/tq?tqx=out:csv&sheet=${encodeURIComponent(tabName)}`;
  try {
    const response = await fetch(url, {
      headers: { 'User-Agent': 'Sunbelt Project Prep Center' },
      next: { revalidate: 300 },
    });
    if (!response.ok) return [];
    return parseCsv(await response.text()).filter(row => row.some(value => value.trim()));
  } catch {
    return [];
  }
}

async function fetchNormalizedPrepScheduleRows(): Promise<CsvRow[]> {
  const rows = await fetchSheetRows(SCORECARD_SHEET_ID, SCORECARD_TABS.msProjectScheduleLive);
  const table = tableFromRows(rows, ['Job_Number', 'Job_Name', 'Start_Date', 'Finish_Date']);
  if (!table.rows.length) return [];
  const header = [
    'Job Number',
    'Job Name',
    'Scheduled Start',
    'Scheduled Finish',
    'Crew',
    'Mobilize Ready?',
    'Weather Risk',
    'Notes',
  ];
  const normalized = table.rows
    .filter(row => cell(row, ['Task_Type'], 3).toLowerCase() === 'project')
    .map(row => {
      const status = displayScheduleStatus(cell(row, ['Schedule_Status'], 13), cell(row, ['Percent_Complete'], 5));
      return [
        cell(row, ['Job_Number'], 0),
        cell(row, ['Job_Name'], 1),
        cell(row, ['Start_Date'], 6),
        cell(row, ['Finish_Date'], 7),
        'MS Project',
        normalizeScheduleStatus(status) === 'COMPLETE' || normalizeScheduleStatus(status) === 'IN_PROGRESS' ? 'YES' : '',
        status,
        [
          cell(row, ['Source_File'], 11) ? `Source: ${cell(row, ['Source_File'], 11)}` : '',
          cell(row, ['Snapshot_Date'], 10) ? `Snapshot: ${cell(row, ['Snapshot_Date'], 10)}` : '',
          cell(row, ['Parse_Status'], 14) ? `Parse: ${cell(row, ['Parse_Status'], 14)}` : '',
        ].filter(Boolean).join(' | '),
      ];
    });
  return [header, ...normalized];
}

async function fetchNormalizedPrepWeatherRows(): Promise<CsvRow[]> {
  const rows = await fetchSheetRows(SCORECARD_SHEET_ID, SCORECARD_TABS.weatherWatch);
  const table = tableFromRows(rows, ['Job #', 'Job Name', 'Alert Level']);
  if (!table.rows.length) return [];
  const header = ['Job Number', 'Job Name', 'Forecast Date', 'Conditions', 'Rain %', 'Risk'];
  const normalized = table.rows.map(row => [
    cell(row, ['Job #'], 0),
    cell(row, ['Job Name'], 1),
    cell(row, ['Date'], 4),
    cell(row, ['Forecast Summary'], 5),
    cell(row, ['Precip %'], 8),
    cell(row, ['Alert Level'], 10),
  ]);
  return [header, ...normalized];
}

async function fetchProjectPrepRentalRows(): Promise<CsvRow[]> {
  const setupRows = await fetchSheetRows(PROJECT_SETUP_SHEET_ID, PROJECT_SETUP_TABS.sunbeltRentalsLive);
  const setupTable = tableFromRows(setupRows, ['Vendor', 'Contract_Number']);
  if (setupTable.rows.length) return setupRows;

  const scorecardRows = await fetchSheetRows(SCORECARD_SHEET_ID, SCORECARD_TABS.onRent);
  const scorecardTable = tableFromRows(scorecardRows, ['Vendor', 'Equipment Description', 'Current Jobsite']);
  if (!scorecardTable.rows.length) return [];
  const header = [
    'Vendor',
    'Contract_Number',
    'Job_Name',
    'Equipment_Type',
    'Days_On_Rent',
    'Pickup_Date',
  ];
  const normalized = scorecardTable.rows.map(row => [
    cell(row, ['Vendor'], 1),
    cell(row, ['Asset ID'], 0),
    cell(row, ['Current Jobsite'], 4),
    cell(row, ['Equipment Description'], 2) || cell(row, ['Equipment Category'], 3),
    cell(row, ['Days on Site'], 9),
    cell(row, ['Expected Release Date'], 7),
  ]);
  return [header, ...normalized];
}

function tableFromRows(rows: CsvRow[], requiredHeaders: string[]) {
  const headerIndex = rows.findIndex(row => {
    const normalized = row.map(normalizeHeader);
    return requiredHeaders.every(header => normalized.includes(normalizeHeader(header)));
  });
  if (headerIndex < 0) return { header: [], rows: [] as Array<Record<string, string> & { __raw: string[] }> };
  const header = rows[headerIndex].map(headerName => headerName.trim());
  const dataRows = rows.slice(headerIndex + 1).map(raw => {
    const row = { __raw: raw } as Record<string, string> & { __raw: string[] };
    header.forEach((headerName, index) => {
      const key = headerName.trim();
      if (key && row[key] === undefined) row[key] = raw[index] || '';
    });
    return row;
  });
  return { header, rows: dataRows };
}

function buildJobBase(row: Record<string, string> & { __raw: string[] }) {
  const raw = row.__raw || [];
  const jobNumber = cell(row, ['Job Number'], 2);
  const lat = parseCoordinate(cell(row, ['Latitude', 'Lat'], 23));
  const lng = parseCoordinate(cell(row, ['Longitude', 'Lng'], 24));
  return {
    jobId: cell(row, ['Job_ID', 'Job ID'], 0),
    jobNumber,
    jobName: cell(row, ['Job Name'], 3),
    wipStatus: cell(row, ['WIP Status'], 4),
    address: cell(row, ['Address', 'Site Address'], 5),
    city: cell(row, ['City'], 6),
    state: cell(row, ['State'], 7),
    generalContractor: cell(row, ['General Contractor'], 8),
    pointOfContact: cell(row, ['Point Of Contact'], 9),
    planDate: cell(row, ['Plan Date'], 10),
    latitude: lat,
    longitude: lng,
    asphaltSource: cell(row, ['Asphalt Source'], 11),
    quarrySource: cell(row, ['Quarry Source'], 12),
    estimatedTons: parseNumber(cell(row, ['Est Tons', 'Estimated Tons'], 13) || raw[13]),
    estimatedLoads: cell(row, ['Est Loads'], 14),
    needs: {
      asphaltPlant: yesNo(cell(row, ['Need Plant'], 15)),
      quarry: yesNo(cell(row, ['Need Quarry'], 16)),
      disposal: yesNo(cell(row, ['Need Disposal'], 17)),
      trucks: yesNo(cell(row, ['Need Trucks'], 18)),
      equipment: yesNo(cell(row, ['Need Equipment'], 19)),
      accountReview: !isNo(cell(row, ['Account Risk'], 20)),
      dumpSetup: yesNo(cell(row, ['Dump Setup'], 21)),
      rentalFocus: yesNo(cell(row, ['Rental Focus'], 22)),
    },
  };
}

function buildResources(
  job: ReturnType<typeof buildJobBase>,
  prepItems: Array<Record<string, string> & { __raw: string[] }>,
): ProjectPrepResource[] {
  const byLabel = indexBy(prepItems, row => cell(row, ['Prep Item'], 4));
  return RESOURCE_ORDER.map(label => {
    const row = byLabel[label];
    const required = isResourceRequired(job, label);
    const primary = cell(row, ['Work Order Need / Vendor'], 5);
    const statusRaw = cell(row, ['Status'], 11) || cell(row, ['Account Status'], 6);
    const status = required ? normalizeResourceStatus(statusRaw, primary) : 'NOT REQUIRED';
    const riskLevel = resourceRisk(status);

    return {
      key: normalizeHeader(label),
      label,
      required,
      primary,
      accountStatus: cell(row, ['Account Status'], 6),
      pendingApp: cell(row, ['Pending App?'], 7),
      alternates: [cell(row, ['Alternate 1'], 8), cell(row, ['Alternate 2'], 9)].filter(Boolean),
      searchCity: cell(row, ['Search / City'], 10),
      status,
      riskLevel,
      nextAction: required ? cell(row, ['Next Action'], 12) || defaultNextAction(label, status) : 'Not required for current scope',
      riskNote: cell(row, ['Risk Note'], 13),
      source: row ? `Sunbelt Project Setup -> ${PROJECT_SETUP_TABS.jobPrepBoard}` : `Missing ${PROJECT_SETUP_TABS.jobPrepBoard} row`,
    };
  });
}

function isResourceRequired(job: ReturnType<typeof buildJobBase>, label: string) {
  if (label === 'Asphalt Plant') return job.needs.asphaltPlant;
  if (label === 'Rock / Quarry') return job.needs.quarry;
  if (label === 'Haulers / Trucks') return job.needs.trucks;
  if (label === 'Dump Site / Debris') return job.needs.disposal || job.needs.dumpSetup;
  if (label === 'Equipment On Rent') return job.needs.equipment || job.needs.rentalFocus;
  return true;
}

function normalizeResourceStatus(value: string, primary: string): ProjectPrepResource['status'] {
  const status = normalizeText(value);
  if (!primary && !status) return 'MISSING';
  if (status.includes('NO ACCOUNT') || status.includes('NOACCOUNT')) return 'NO ACCOUNT';
  if (status.includes('READY') || status === 'OPEN' || status.includes('ACCOUNT OPEN')) return 'READY';
  if (status.includes('CHECK') || status.includes('REVIEW') || status.includes('PENDING')) return 'CHECK';
  return primary ? 'CHECK' : 'MISSING';
}

function resourceRisk(status: ProjectPrepResource['status']): ProjectPrepResource['riskLevel'] {
  if (status === 'READY') return 'ready';
  if (status === 'NO ACCOUNT' || status === 'MISSING') return 'blocked';
  if (status === 'NOT REQUIRED') return 'neutral';
  return 'watch';
}

function buildBlockers(jobNumber: string, resources: ProjectPrepResource[]): ProjectPrepBlocker[] {
  return resources
    .filter(resource => resource.required && resource.riskLevel !== 'ready')
    .map(resource => ({
      jobNumber,
      label: resource.label,
      severity: resource.riskLevel === 'blocked' ? 'blocked' : 'watch',
      reason: resource.riskNote || `${resource.label} status is ${resource.status}`,
      nextAction: resource.nextAction,
      source: resource.source,
    }));
}

function buildReadiness(
  job: ReturnType<typeof buildJobBase>,
  parsedRow: (Record<string, string> & { __raw: string[] }) | undefined,
  scheduleRow: (Record<string, string> & { __raw: string[] }) | undefined,
  resources: ProjectPrepResource[],
  blockers: ProjectPrepBlocker[],
) {
  const required = resources.filter(resource => resource.required);
  const readyCount = required.filter(resource => resource.riskLevel === 'ready').length;
  const watchCount = required.filter(resource => resource.riskLevel === 'watch').length;
  const blockerCount = required.filter(resource => resource.riskLevel === 'blocked').length;
  const requiredCount = required.length;
  const readyPercent = requiredCount ? Math.round((readyCount / requiredCount) * 100) : 100;
  const scheduledStart = cell(scheduleRow, ['Scheduled Start'], 4);
  const mobilizeReady = normalizeText(cell(scheduleRow, ['Mobilize Ready?'], 7));
  const status = blockerCount > 0 ? 'BLOCKED' : watchCount > 0 ? 'REVIEW' : 'READY';

  return {
    readyCount,
    requiredCount,
    watchCount,
    blockerCount,
    readyPercent,
    status,
    funnel: [
      {
        label: 'Job instantiated',
        complete: Boolean(job.jobNumber && job.jobName),
        detail: `${PROJECT_SETUP_TABS.activeJobs} row present`,
      },
      {
        label: 'Scope parsed',
        complete: Boolean(parsedRow),
        detail: parsedRow ? `${PREP_AUTOMATION_TABS.parsedJobs} row present` : `Missing ${PREP_AUTOMATION_TABS.parsedJobs} match`,
      },
      {
        label: 'Resources configured',
        complete: readyCount === requiredCount && requiredCount > 0,
        detail: `${readyCount}/${requiredCount} required resources ready`,
      },
      {
        label: 'Schedule checked',
        complete: Boolean(scheduledStart) || mobilizeReady === 'YES',
        detail: scheduledStart || `Mobilize Ready: ${cell(scheduleRow, ['Mobilize Ready?'], 7) || 'blank'}`,
      },
      {
        label: 'Go-live clear',
        complete: blockers.length === 0,
        detail: blockers.length ? `${blockers.length} blockers/watch items open` : 'No open blockers',
      },
    ],
  } as ProjectPrepJob['readiness'];
}

function buildLinks(
  job: ReturnType<typeof buildJobBase>,
  parsedRow: (Record<string, string> & { __raw: string[] }) | undefined,
  docsRow: (Record<string, string> & { __raw: string[] }) | undefined,
): ProjectPrepJob['links'] {
  return {
    level10: `https://docs.google.com/spreadsheets/d/${LEVEL10_SHEET_ID}/edit`,
    projectSetup: `https://docs.google.com/spreadsheets/d/${PROJECT_SETUP_SHEET_ID}/edit`,
    prepAutomation: `https://docs.google.com/spreadsheets/d/${PREP_AUTOMATION_SHEET_ID}/edit`,
    scorecard: `https://docs.google.com/spreadsheets/d/${SCORECARD_SHEET_ID}/edit`,
    jobFolder: cell(parsedRow, ['Job Folder Link'], 3),
    workOrder: cell(docsRow, ['Work Order'], 3) || cell(parsedRow, ['Work Order Link'], 2),
    costSheet: cell(docsRow, ['Cost Sheet'], 2),
    plans: cell(docsRow, ['Plans'], 4),
    contract: cell(docsRow, ['Contract'], 5),
  };
}

async function fetchLiveWeather(jobs: Array<ReturnType<typeof buildJobBase>>) {
  const entries = await Promise.all(jobs.map(async job => {
    if (job.latitude === null || job.longitude === null) return [job.jobNumber, null] as const;
    try {
      const url = `https://api.open-meteo.com/v1/forecast?latitude=${job.latitude}&longitude=${job.longitude}&daily=precipitation_probability_max,weathercode,temperature_2m_max&temperature_unit=fahrenheit&timezone=America%2FNew_York&forecast_days=3`;
      const response = await fetch(url, { next: { revalidate: 21600 } });
      if (!response.ok) return [job.jobNumber, null] as const;
      const json = await response.json();
      const probability = Number(json?.daily?.precipitation_probability_max?.[0]);
      return [job.jobNumber, {
        forecastDate: String(json?.daily?.time?.[0] || ''),
        rainPercent: Number.isFinite(probability) ? probability : null,
        conditions: weatherCodeToText(Number(json?.daily?.weathercode?.[0])),
      }] as const;
    } catch {
      return [job.jobNumber, null] as const;
    }
  }));
  return Object.fromEntries(entries);
}

function buildWeather(
  job: ReturnType<typeof buildJobBase>,
  weatherRow: (Record<string, string> & { __raw: string[] }) | undefined,
  live: { forecastDate: string; rainPercent: number | null; conditions: string } | null,
): ProjectPrepJob['weather'] {
  const sheetRain = parseNumber(cell(weatherRow, ['Rain %', 'Precip %'], 5));
  const rainPercent = live?.rainPercent ?? (sheetRain || null);
  const conditions = live?.conditions || cell(weatherRow, ['Conditions', 'Forecast Summary'], 6) || 'No forecast loaded';
  const risk = rainPercent === null
    ? cell(weatherRow, ['Risk', 'Alert Level'], 7) || 'UNKNOWN'
    : rainPercent >= 60 ? 'HIGH'
      : rainPercent >= 35 ? 'WATCH'
        : 'OK';

  return {
    forecastDate: live?.forecastDate || cell(weatherRow, ['Forecast Date', 'Date'], 4),
    rainPercent,
    conditions,
    risk,
    source: live ? `Open-Meteo live forecast by ${PROJECT_SETUP_TABS.activeJobs} coordinates` : `Sunbelt Sports Scorecard -> ${SCORECARD_TABS.weatherWatch}`,
  };
}

function buildNearbyJobs(job: ReturnType<typeof buildJobBase>, jobs: Array<ReturnType<typeof buildJobBase>>) {
  if (job.latitude === null || job.longitude === null) return [];
  return jobs
    .filter(other => other.jobNumber !== job.jobNumber && other.latitude !== null && other.longitude !== null)
    .map(other => ({
      jobNumber: other.jobNumber,
      jobName: other.jobName,
      city: other.city,
      state: other.state,
      miles: Math.round(distanceMiles(job.latitude!, job.longitude!, other.latitude!, other.longitude!)),
    }))
    .sort((a, b) => a.miles - b.miles)
    .slice(0, 4);
}

function buildEquipment(
  job: ReturnType<typeof buildJobBase>,
  rentalsRows: Array<Record<string, string> & { __raw: string[] }>,
  equipmentRows: Array<Record<string, string> & { __raw: string[] }>,
): ProjectPrepJob['equipment'] {
  const jobKey = normalizeLookup(job.jobName);
  const rentals = rentalsRows
    .filter(row => normalizeLookup(cell(row, ['Job_Name'], 3)).includes(jobKey) || jobKey.includes(normalizeLookup(cell(row, ['Job_Name'], 3))))
    .slice(0, 8)
    .map(row => ({
      vendor: cell(row, ['Vendor'], 0),
      contractNumber: cell(row, ['Contract_Number'], 1),
      equipmentType: cell(row, ['Equipment_Type'], 8) || cell(row, ['Class_Name'], 9),
      daysOnRent: Math.round(parseNumber(cell(row, ['Days_On_Rent'], 14))),
      pickupDate: cell(row, ['Pickup_Date'], 15),
    }));

  const assets = equipmentRows.slice(0, 8).map(row => {
    const latLong = cell(row, ['LatLong'], 3);
    const [latFromCombined, lngFromCombined] = latLong.split(',').map(parseCoordinate);
    const lat = parseCoordinate(cell(row, ['Latitude'], 6)) ?? latFromCombined ?? null;
    const lng = parseCoordinate(cell(row, ['Longitude'], 7)) ?? lngFromCombined ?? null;
    const miles = job.latitude !== null && job.longitude !== null && lat !== null && lng !== null
      ? Math.round(distanceMiles(job.latitude, job.longitude, lat, lng))
      : null;
    return {
      assetId: cell(row, ['AssetID', 'Asset ID'], 0),
      make: cell(row, ['Make'], 2),
      model: cell(row, ['Model'], 3),
      status: cell(row, ['Status'], 10),
      lastReported: cell(row, ['LastReportedTime', 'Last Reported', 'Last Ping', 'Updated At'], 11),
      distanceMiles: miles,
    };
  });

  return { rentals, assets };
}

function buildActions(
  job: ReturnType<typeof buildJobBase>,
  blockers: ProjectPrepBlocker[],
  links: ProjectPrepJob['links'],
): ProjectPrepJob['actions'] {
  const subject = encodeURIComponent(`${job.jobNumber} ${job.jobName} setup needed`);
  const body = encodeURIComponent(`Project Prep item for ${job.jobNumber} ${job.jobName}\n\nJob location: ${job.city}, ${job.state}\n\nOpen item:\n`);
  const blockerActions = blockers.slice(0, 4).map(blocker => ({
    label: blocker.nextAction || `Resolve ${blocker.label}`,
    href: `mailto:?subject=${subject}&body=${body}${encodeURIComponent(`${blocker.label}: ${blocker.reason}`)}`,
    source: blocker.source,
  }));

  return [
    ...blockerActions,
    links.workOrder ? { label: 'Open work order', href: links.workOrder, source: `${PREP_AUTOMATION_TABS.parsedJobs} / ${PROJECT_SETUP_TABS.jobDocs}` } : null,
    links.jobFolder ? { label: 'Open project folder', href: links.jobFolder, source: PREP_AUTOMATION_TABS.parsedJobs } : null,
  ].filter(Boolean) as ProjectPrepJob['actions'];
}

function detectContractIssues(
  activeRows: CsvRow[],
  activeHeader: string[],
  prepRows: Array<Record<string, string> & { __raw: string[] }>,
  scheduleRows: Array<Record<string, string> & { __raw: string[] }>,
) {
  const issues: string[] = [];
  if (activeHeader[13] === '') issues.push('Active_Jobs column N is blank in public CSV export; app maps estimated tons by fixed fallback column N.');
  if (activeHeader[23] && /^-?\d+(\.\d+)?$/.test(activeHeader[23])) issues.push('Active_Jobs latitude/longitude headers are bad numeric values; app maps coordinates by fixed columns X/Y.');
  const prepJobCount = new Set(prepRows.map(row => cell(row, ['Job Number'], 1)).filter(Boolean)).size;
  const activeJobCount = Math.max(0, activeRows.length - 1);
  if (prepJobCount && activeJobCount && prepJobCount < activeJobCount) issues.push('Job_Prep_Board has fewer job groups than Active_Jobs; missing jobs will show missing resource rows.');
  const malformedSchedule = scheduleRows.filter(row => cell(row, ['Job Number'], 0) && !/^\d{2}-\d{3}$/.test(cell(row, ['Job Number'], 0))).length;
  if (malformedSchedule) issues.push('Schedule contains non-standard job numbers; app only joins exact YY-NNN job numbers.');
  return issues;
}

function cell(row: (Record<string, string> & { __raw: string[] }) | undefined, names: string[], fallbackIndex?: number): string {
  if (!row) return '';
  for (const name of names) {
    if (row[name] !== undefined && row[name] !== '') return String(row[name]).trim();
    const key = Object.keys(row).find(existing => normalizeHeader(existing) === normalizeHeader(name));
    if (key && row[key] !== undefined && row[key] !== '') return String(row[key]).trim();
  }
  if (fallbackIndex !== undefined) return String(row.__raw?.[fallbackIndex] || '').trim();
  return '';
}

function indexBy<T>(items: T[], keyFn: (item: T) => string) {
  return items.reduce<Record<string, T>>((acc, item) => {
    const key = keyFn(item);
    if (key && acc[key] === undefined) acc[key] = item;
    return acc;
  }, {});
}

function groupBy<T>(items: T[], keyFn: (item: T) => string) {
  return items.reduce<Record<string, T[]>>((acc, item) => {
    const key = keyFn(item);
    if (!key) return acc;
    if (!acc[key]) acc[key] = [];
    acc[key].push(item);
    return acc;
  }, {});
}

function normalizeHeader(value: string) {
  return String(value || '').toLowerCase().replace(/[^a-z0-9]+/g, '');
}

function normalizeText(value: string) {
  return String(value || '').toUpperCase().replace(/\s+/g, ' ').trim();
}

function normalizeLookup(value: string) {
  return String(value || '').toLowerCase().replace(/[^a-z0-9]+/g, '');
}

function yesNo(value: string) {
  return normalizeText(value) === 'YES' || normalizeText(value) === 'TRUE';
}

function isNo(value: string) {
  return normalizeText(value) === 'NO' || normalizeText(value) === 'FALSE';
}

function parseNumber(value: string) {
  const n = Number(String(value || '').replace(/[^0-9.-]+/g, ''));
  return Number.isFinite(n) ? n : 0;
}

function parseCoordinate(value: string) {
  const n = Number(String(value || '').replace(/[^0-9.-]+/g, ''));
  return Number.isFinite(n) ? n : null;
}

function defaultNextAction(label: string, status: ProjectPrepResource['status']) {
  if (status === 'NO ACCOUNT') return `Start credit app for ${label}`;
  if (status === 'MISSING') return `Assign ${label}`;
  return `Verify ${label}`;
}

function parseCsv(text: string): string[][] {
  const rows: string[][] = [];
  let row: string[] = [];
  let value = '';
  let inQuotes = false;
  for (let i = 0; i < text.length; i++) {
    const char = text[i];
    if (inQuotes) {
      if (char === '"') {
        if (text[i + 1] === '"') {
          value += '"';
          i++;
        } else {
          inQuotes = false;
        }
      } else {
        value += char;
      }
      continue;
    }
    if (char === '"') inQuotes = true;
    else if (char === ',') {
      row.push(value);
      value = '';
    } else if (char === '\n' || char === '\r') {
      row.push(value);
      rows.push(row);
      row = [];
      value = '';
      if (char === '\r' && text[i + 1] === '\n') i++;
    } else {
      value += char;
    }
  }
  if (value || row.length) {
    row.push(value);
    rows.push(row);
  }
  return rows;
}

function distanceMiles(lat1: number, lng1: number, lat2: number, lng2: number) {
  const radius = 3958.8;
  const dLat = toRadians(lat2 - lat1);
  const dLng = toRadians(lng2 - lng1);
  const a = Math.sin(dLat / 2) ** 2
    + Math.cos(toRadians(lat1)) * Math.cos(toRadians(lat2)) * Math.sin(dLng / 2) ** 2;
  return radius * 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
}

function toRadians(value: number) {
  return value * Math.PI / 180;
}

function weatherCodeToText(code: number) {
  if ([0].includes(code)) return 'Clear';
  if ([1, 2, 3].includes(code)) return 'Cloud cover';
  if ([45, 48].includes(code)) return 'Fog';
  if ([51, 53, 55, 56, 57].includes(code)) return 'Drizzle';
  if ([61, 63, 65, 66, 67, 80, 81, 82].includes(code)) return 'Rain';
  if ([71, 73, 75, 77, 85, 86].includes(code)) return 'Snow';
  if ([95, 96, 99].includes(code)) return 'Thunderstorm';
  return 'Forecast loaded';
}
